version: '3.4'

services:
  nestb12:
    image: nestb12
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5001:5000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
